Don't check SSL certificate with wget
This is needed especially to download e-c-m on Travis CI because
download.kde.org sometimes redirect to SSL web sites.

Avoids issues such as this:

$ wget http://download.kde.org/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz
--2015-08-04 22:04:04--  http://download.kde.org/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz
Resolving download.kde.org (download.kde.org)... 2001:67c:2178:7::71, 195.135.221.71
Connecting to download.kde.org (download.kde.org)|2001:67c:2178:7::71|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://kde.cu.be/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz [following]
--2015-08-04 22:04:05--  http://kde.cu.be/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz
Resolving kde.cu.be (kde.cu.be)... 2001:67c:314::feed:feef, 194.50.97.34
Connecting to kde.cu.be (kde.cu.be)|2001:67c:314::feed:feef|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://kde.cu.be/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz [following]
--2015-08-04 22:04:05--  https://kde.cu.be/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz
Connecting to kde.cu.be (kde.cu.be)|2001:67c:314::feed:feef|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name `kde.cu.be'.
To connect to kde.cu.be insecurely, use `--no-check-certificate'.

The command "wget http://download.kde.org/stable/frameworks/5.12/extra-cmake-modules-5.12.0.tar.xz" failed and exited with 5 during .